apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: todo-namespace
spec:
  selector:
    app: frontend
  ports: 
    - protocol: TCP
      port: 3000
      targetPort: 3000 
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: frontend
  namespace: todo-namespace
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 2
  template:
    metadata:
      labels: 
        app: frontend
    spec:
      containers:
        - name: frontend
          image: teak16/todoappimg-frontend
          imagePullPolicy: Always
          ports:
            - containerPort: 3000

            
