apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: todo-namespace
  labels:
    name: backend
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: backend
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: todo-namespace
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 2
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: teak16/todoappimg-backend
          ports:
            - containerPort: 8080
          env:
            - name: HOST_DB
              valueFrom:
                configMapKeyRef:
                  name: postgres-conf
                  key: host
            - name: NAME_DB
              valueFrom:
                configMapKeyRef:
                  name: postgres-conf
                  key: name
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: postgres_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: postgres_password

