apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: psql-db-pv-claim
  namespace: todo-namespace
  labels:
    app: psql-db
    tier: database
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi



