apiVersion: v1
kind: Service
metadata:
  name: psql-db
  namespace: todo-namespace
  labels:
    app: psql-db
    tier: database
spec:
  ports:
    - port: 5432
  selector:
    app: psql-db
    tier: database
  clusterIP: None 
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: psql-db
  namespace: todo-namespace
spec:
  serviceName: psql-db
  selector:
    matchLabels:
      app: psql-db
  replicas: 1
  template:
    metadata:
      labels:
        app: psql-db
        tier: database
    spec:
      containers:
        - name: psql-db
          image: postgres
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: postgres_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: postgres_password
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: postgres-conf
                  key: name
          ports:
            - containerPort: 5432
              name: psql-db
          volumeMounts:
            - name: postgres-persistence-storage  
              mountPath: /var/lib/postgresql/data  
      volumes:
        - name: postgres-persistence-storage
          persistentVolumeClaim:
            claimName: psql-db-pv-claim

