name: Docker Build and Push

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and push Backend Docker image
        working-directory: ToDoList
        env:
          Docker: ${{DOCKER_USERNAME}}
          Docker: ${{DOCKER_PASSWORD}}
          IMAGE_NAME_BACKEND: teak16/todoappimg
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker build -t $IMAGE_NAME_BACKEND .
          docker push $IMAGE_NAME_BACKEND

      - name: Build and push Frontend Docker image
        working-directory: frontend
        env:
          Docker: ${{DOCKER_USERNAME}}
          Docker: ${{DOCKER_PASSWORD}}
          IMAGE_NAME_FRONTEND: teak16/todoappimg
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker build -t $IMAGE_NAME_FRONTEND .
          docker push $IMAGE_NAME_FRONTEND
